#!/usr/bin/env python3
"""Generate ArUco marker boards; dictionary choice: model-sources.md 2.3."""

import argparse
import os

import cv2
import numpy as np

BOARD_METRES = 1.0
MARKER_METRES = 0.5
DICTIONARY = cv2.aruco.DICT_4X4_50


def render_board(marker_id, board_pixels):
    """White board, marker centred, leaving the quiet zone ArUco needs."""
    marker_pixels = int(round(board_pixels * MARKER_METRES / BOARD_METRES))
    dictionary = cv2.aruco.Dictionary_get(DICTIONARY)
    marker = cv2.aruco.drawMarker(dictionary, marker_id, marker_pixels)

    board = np.full((board_pixels, board_pixels), 255, dtype=np.uint8)
    offset = (board_pixels - marker_pixels) // 2
    board[offset:offset + marker_pixels, offset:offset + marker_pixels] = marker
    return board


def write_model(model_root, marker_id, board_pixels):
    name = f'aruco_{marker_id}'
    model_dir = os.path.join(model_root, name)
    texture_dir = os.path.join(model_dir, 'materials', 'textures')
    mesh_dir = os.path.join(model_dir, 'materials', 'meshes')
    os.makedirs(texture_dir, exist_ok=True)
    os.makedirs(mesh_dir, exist_ok=True)

    board = render_board(marker_id, board_pixels)
    cv2.imwrite(os.path.join(texture_dir, f'{name}.png'), board)

    half = BOARD_METRES / 2.0
    with open(os.path.join(mesh_dir, f'{name}.obj'), 'w', newline='\n') as obj:
        obj.write(f'mtllib {name}.mtl\n')
        obj.write(f'v {-half} {-half} 0\nv {half} {-half} 0\n')
        obj.write(f'v {half} {half} 0\nv {-half} {half} 0\n')
        # Flipping v mirrors the marker (UV bug); package-status.md ArUco traps.
        obj.write('vt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\n')
        obj.write('vn 0 0 1\n')
        obj.write(f'usemtl {name}\n')
        obj.write('f 1/1/1 2/2/1 3/3/1 4/4/1\n')

    with open(os.path.join(mesh_dir, f'{name}.mtl'), 'w', newline='\n') as mtl:
        mtl.write(f'newmtl {name}\n')
        mtl.write('Ka 1.000 1.000 1.000\nKd 1.000 1.000 1.000\nKs 0.000 0.000 0.000\n')
        mtl.write('illum 1\nd 1.0\n')
        mtl.write(f'map_Kd ../textures/{name}.png\n')

    with open(os.path.join(model_dir, 'model.sdf'), 'w', newline='\n') as sdf:
        sdf.write(f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate_aruco_marker.py. Do not edit. -->
<sdf version="1.9">
  <model name="{name}">
    <static>true</static>
    <link name="link">
      <visual name="visual">
        <geometry>
          <mesh>
            <uri>model://{name}/materials/meshes/{name}.obj</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
  </model>
</sdf>
''')

    with open(os.path.join(model_dir, 'model.config'), 'w', newline='\n') as config:
        config.write(f'''<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>
    ArUco {name} on a {BOARD_METRES:.1f} m board, marker edge {MARKER_METRES:.1f} m,
    dictionary DICT_4X4_50. Generated at build time; not checked in.

    No collision on purpose: this is a pattern painted on the ground, and giving
    it a collision box would put an invisible step under the landing gear.
  </description>
</model>
''')
    return model_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', required=True, help='directory to write models into')
    parser.add_argument('--ids', type=int, nargs='+', default=[7, 17])
    parser.add_argument('--pixels', type=int, default=1000, help='board texture side')
    args = parser.parse_args()

    for marker_id in args.ids:
        path = write_model(args.out, marker_id, args.pixels)
        print(f'aruco_{marker_id}: board {BOARD_METRES} m, marker {MARKER_METRES} m '
              f'-> {path}')


if __name__ == '__main__':
    main()
